name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set
    container:
      image: gcr.io/kaniko-project/executor:debug

    steps:
      - name: Checkout Another Repository
        uses: actions/checkout@v4
